### ISSUE TITLE
PITest fails with large stacktrace when using `junit5` and Spek

### ISSUE THREAD

**Issue by snowe2010** [szpak/gradle-pitest-plugin#110]
```
pretty-print on  pitest took 3s
➜ ./gradlew pitest                                                                                                                                                                  

> Configure project :
Inferred project: pretty-print, version: 1.3.0-dev.2+pitest.68a97e6

> Task :pitest FAILED
9:53:14 PM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
9:53:14 PM PIT >> INFO : Sending 91 test classes to minion
9:53:14 PM PIT >> INFO : Sent tests to minion
9:53:15 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.192-b12
Uptime : 621
Input ->
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.192-b12
Uptime : 622
Input ->
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.192-b12
Uptime : 621
Input ->
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:147)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
        ... 6 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pitest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
```

A reproducible example is available [here](https://github.com/snowe2010/pretty-print/tree/68a97e6c3a940330300b7083ddb8184d030e5067)

I cannot get pitest to work in any way whatsoever though, so this might not be related to the junit5 plugin

**Comment by snowe2010** [comment]
It appears you need to specify 

```kotlin

buildscript {
    repositories {
        mavenCentral()
    }
    configurations.maybeCreate("pitest")
    dependencies {
        "pitest"("org.pitest:pitest-junit5-plugin:0.8")
    }
}
```
in order to provide the junit5 plugin.

**Comment by szpak** [comment]
You may also need to add:

```
pitest {
    testPlugin = 'junit5'
}
```

Using plugins is clearly described in README: https://github.com/szpak/gradle-pitest-plugin#pit-test-plugins-support

**Comment by snowe2010** [comment]
Yes, I'm sorry I had the `testPlugin` line, but not the buildscript line. I apparently missed that on the website.

**Comment by vasilej-yopeso** [comment]
Still fails with 
```
    classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.5.0'
    pitest 'org.pitest:pitest-junit5-plugin:0.12'
```

It works with the exact same configuration but with pitest plugin version 1.4.8

```
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : AdoptOpenJDK
Version : 12.0.2+10
Uptime : 1468
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : AdoptOpenJDK
Version : 12.0.2+10
Uptime : 1469
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:121)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:51)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : AdoptOpenJDK
Version : 12.0.2+10
Uptime : 1468
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:148)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	... 6 more
```

**Comment by szpak** [comment]
@vasilej-yopeso Do you also have JUnit 5 and Spek? Please create a separate issue and precise what gradle-pitest-plugin and PIT versions you use, that is your configuration (all plugin related parts) and if possible paste a link to your project.
