### ISSUE TITLE
Better error message on missing test plugin

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#129]
Here in TestNG project PIT (1.4.8) fails with not the most intuitive error message if TestNG plugin is not activated:
```
Successfully started process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc29.x86_64/bin/java''
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.212-b04
Uptime : 629
Input -> 
 1 : -Djava.util.logging.config.file=/tmp/logging.properties
 2 : -Dfile.encoding=UTF-8
 3 : -Duser.country=US
 4 : -Duser.language=en
 5 : -Duser.variant
BootClassPathSupported : true
(...)
        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
(...)

        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:142)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
        ... 6 more
:pitest (Thread[Task worker for ':',5,main]) completed. Took 0.714 secs.
```

**Comment by szpak** [comment]
Looking in PIT code:
```
    if (exitCode == ExitCode.JUNIT_ISSUE) {
      LOG.severe("Error generating coverage. Please check that your classpath contains JUnit 4.6 or above.");
      throw new PitError(
"Coverage generation minion exited abnormally. Please check the classpath.");
```
there should be the "severe" message about JUnit, but it is not displayed when executing from Gradle with `--info`. Maybe this exception message could be also improved.

**Comment by szpak** [comment]
Should be better in PIT 1.5.0.
