### ISSUE TITLE
Plugin execution on windows fails with CreateProcess error 206

### ISSUE THREAD

**Issue by Saladoc** [szpak/gradle-pitest-plugin#335]
# What happens?
When executing the pitest phase on windows, the build fails with an exception.

``` * Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pitest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:\Program Files\GraalVM\graalvm-ce-java17-22.3.1\bin\java.exe''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'C:\Program Files\GraalVM\graalvm-ce-java17-22.3.1\bin\java.exe'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
        ... 3 more
Caused by: java.io.IOException: Cannot run program "C:\Program Files\GraalVM\graalvm-ce-java17-22.3.1\bin\java.exe" (in directory "E:\Programmierung\Java\Tracktor"): CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu
 lang
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
Caused by: java.io.IOException: CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang
        ... 8 more
``` 

# Is it really the pitest plugins fault?
The error does not occur if the pitest phase is skipped or the build is executed on a linux based system. I tested with `docker container run -it --rm -v "E:/Path/To/My/Project/:/code" openjdk:17-slim sh -c 'cd /code && ./gradlew clean build'` and the build finished flawlessly. Either the plugin or a dependency or API contains a windows specific bug.

# Obligatory Version and Environment Info

`gradlew --version`:
```------------------------------------------------------------
Gradle 8.1
------------------------------------------------------------

Build time:   2023-04-12 12:07:45 UTC
Revision:     40ba32cde9d6daf2b92c39376d2758909dd6b813

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (GraalVM Community 17.0.6+10-jvmci-22.3-b13)
OS:           Windows 10 10.0 amd64
```

Plugin Version: `1.9.11`
Junit 5 Plugin Version: `1.1.2`

Plugin configuration (in build.gradle.kts): 
```kotlin
tasks.test {
    // ...
    finalizedBy(tasks.pitest)
}

tasks.pitest {
    dependsOn(tasks.test)
}

pitest {
    junit5PluginVersion.set(libs.versions.pitestJUnit5)
}```

**Comment by C-Otto** [comment]
Note that "Der Dateiname oder die Erweiterung ist zu lang" is German for "file name or (file) extension is too long". Windows has some strange limits on how long a path may be. It might help to move your java.exe (and surroundings) from `C:\Program Files\GraalVM\graalvm-ce-java17-22.3.1\bin\java.exe`  to some shorter location like `c:\dev\jvm\bin\java.exe`. My suggestion: don't use Windows.

**Comment by szpak** [comment]
> My suggestion: don't use Windows.

That is some solution ;-), but if you really stuck with Windows, you can use two magic configuration properties to mitigate that limitation:

```
pitest {
    ...
    useClasspathFile = true
    useClasspathJar = true
}
```

There is a chance, only one the aforementioned is needed, but in the future PIT versions they will be paired by default anyway (https://github.com/hcoles/pitest/pull/1187).

**Comment by Saladoc** [comment]
> My suggestion: don't use Windows.

That's defnitly a suggestion. A java tool should work on all supported operating systems though. Sure, it's a windows problem or perculiarity at the core, but I would expect it to work out of the box - having a couple of dependencies is really to be expected. That being said, the configuration properties solved the problem - even setting only `useClasspathFile`.

**Comment by szpak** [comment]
Great, you are welcome.
