### ISSUE TITLE
Unable to debug a test, that is failing without mutation

### ISSUE THREAD

**Issue by eratynsk** [szpak/gradle-pitest-plugin#370]
Hi!
I'm setting up pitest in java 21 and gradle repo. I have a test failing without mutation, that normally passes green when it's triggered without pitest. 
```
Exception in thread "main" org.pitest.help.PitHelpError: 1 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
See https://pitest.org for more details.
        at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:127)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:109)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:53)
        at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:136)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:136)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:63)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```

I wanted to debug it's execution with pitest, but I'm not sure how to do it.
I'm using the following extension config, but breakpoints are not working in the test's code:
```
configure<PitestPluginExtension> {
    pitestVersion = "1.15.3"
    junit5PluginVersion.set("1.2.1")
    targetClasses.set(setOf("com.example.*"))
    targetTests.set(setOf("com.example.*"))
    verbose=true
    mainProcessJvmArgs.set(listOf("-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"))
}
```

I've seen in [existing issue](https://github.com/szpak/gradle-pitest-plugin/issues/111) that it's possible to debug the test execution by minion (separate jvm process?), could you please share how to do it? 
@szpak

**Comment by szpak** [comment]
Sorry for late reply @eratynsk ... Is that issue still valid for you? If yes, I will try to finally write a blog post about it (as it was not trival AFAIR :-/).

**Comment by Vampire** [comment]
This is a valid issue
It is a documentation issue of PIT itself.
But could also be improved in the plugin here.

There are two things to change in your configuration with current versions.
1. the `mainProcessJvmArgs` are for - well - the main process where PIT itself runs, but the tests are run in child processes,
so you need to either set `jvmArgs` on the extension or `childProcessJvmArgs` on the task.
2. these arguments are interpreted by PIT as comma-separated list of arguments, so if you give `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005` as child process JVM arg, PIt will supply the four arguments `-agentlib:jdwp=transport=dt_socket`, `server=y`, `suspend=y`, and `address=5005` to the child process which does not work of course. The commas have to be within a curly-brace pair to be handled as part of the argument, so you can for example set `-agentlib:jdwp={transport=dt_socket,server=y,suspend=y,address=5005}` or `{-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005}` and it will work as expected.

The splitting and escaping algorithm in PIT is a bit naive, so you for example cannot escape a curly brace in any way.
And as soon as there is one escaped comma, all curly braces are stripped away.
So there is currently no way to supply `-DsomeValue=,{` as arg, because like that it would be `-DsomeValue=` and `{`, and if you do it like `-DsomeValue={,}{` it would be `-DsomeValue=,` with the curly brace missing.

I'll report this last mentioned shortcoming to PIT.

For this plugin, I'd say it is safe to assume that each of the configured child process jvm args is to be considered a full argument, so the curly braces could be inserted automatically.

Naively you could just wrap each argument completely into one pair of curly-braces.
But hoping that after my report to PIT `-DsomeValue={,}{` it would be interpreted as `-DsomeValue=,{`,
I'd suggest that the child process args get all `,` replaced by `{,}` automatically, that should work properly in all cases except if there is a curly brace and a comma in an arg but this is currently not solvable anyway.
This should also be a non-breaking change even if someone already supplied the curly braces explicitly as all get stripped if an escaped comma was found currently.

And with that that tactic it should then hopefully also work with future PIT versions where the `-DsomeValue={,}{` case is fixed.
