### ISSUE TITLE
Exception thrown when no tests in project

### ISSUE THREAD

**Issue by mathiasbn** [szpak/gradle-pitest-plugin#46]
I would like to just apply the pitest plugin to 'allprojects', but not all of my subprojects have tests.

I get:
```
org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
See http://pitest.org for more details.
	at org.pitest.mutationtest.tooling.MutationCoverage.checkMutationsFound(MutationCoverage.java:272)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:136)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:103)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:45)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:76)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```

**Comment by szpak** [comment]
This is a default behavior of PIT. It can be overridden by setting `pitest { failWhenNoMutations = false }`, but it's rather not a good idea. It most of the cases I encounter sooner or later more things  shouldn't (cannot) be applied on the modules without source code at all or just without tests. You could create a subset of "normal" subproject and apply pitest plugin only there.

```
Set emptySubprojects = [project(':docs'), project(':api')]
Set srcSubprojects = subprojects - emptySubprojects

configure(srcSubprojects) {
   ...
}
```
It's Gradle, so those modules could be probably also found automatically if it is not a constant list.

Would it be enough for you?

**Comment by szpak** [comment]
Closing due to inactivity.
