### ISSUE TITLE
gradle pitest failing

### ISSUE THREAD

**Issue by rohit05sharma** [szpak/gradle-pitest-plugin#47]
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.65-b01
Uptime : 559
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:25)
	at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:116)
	at org.pitest.classpath.ArchiveClassPathRoot.getData(ArchiveClassPathRoot.java:45)
	at org.pitest.classpath.CompoundClassPathRoot.getData(CompoundClassPathRoot.java:25)
	at org.pitest.classpath.ClassPath.getClassData(ClassPath.java:100)
	at org.pitest.classpath.ClassPathByteArraySource.getBytes(ClassPathByteArraySource.java:40)
	at org.pitest.classinfo.Repository.querySource(Repository.java:81)
	at org.pitest.classinfo.Repository.nameToClassInfo(Repository.java:67)
	at org.pitest.classinfo.Repository.fetchClass(Repository.java:59)
	at org.pitest.mutationtest.config.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:50)
	at org.pitest.mutationtest.config.LegacyTestFrameworkPlugin.createTestFrameworkConfiguration(LegacyTestFrameworkPlugin.java:34)
	at org.pitest.mutationtest.config.SettingsFactory.getTestFrameworkPlugin(SettingsFactory.java:130)
	at org.pitest.mutationtest.config.SettingsFactory.createCoverageOptions(SettingsFactory.java:137)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:78)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:72)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:114)
	... 15 more
:MAAS:registration-services:pitest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MAAS:registration-services:pitest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by szpak** [comment]
Closing here as you [reported](https://groups.google.com/forum/#!topic/pitusers/Bxks-arQBlk) it also on the mailing list and it seems to be not Gradle specific.
