### ISSUE TITLE
Exception thrown when dynamic libs (.so, .dll, .dylib) are in gradle project classpath.

### ISSUE THREAD

**Issue by amirfarzad** [szpak/gradle-pitest-plugin#52]
I'm recieving the following pi-test exception when I have local dynamoDB (sqlite4java) lib files in my java project with a gradle build. Seems "Pitest gradle plugin" tries to open the lib files in class path and fails on .so file.
Could not find a way to exclude lib files from pi-test either (excludedClasses etc. does not work for .so, .dll, .dylib files even though I excluded "com.almworks.sqlite4java". Still tries to uncompress them).

```
Exception in thread "main" org.pitest.util.PitError: error in opening zip file (/Users/user1/.gradle/caches/modules-2/files-2.1/com.almworks.sqlite4java/libsqlite4java-linux-i386/1.0.392/b193c62571061e68bddeaf8ee7d3a8569b945ea6/libsqlite4java-linux-i386-1.0.392.so)

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.102-b14
Uptime : 323
Input ->
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:25)
        at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:120)
        at org.pitest.classpath.ArchiveClassPathRoot.getData(ArchiveClassPathRoot.java:46)
        at org.pitest.classpath.CompoundClassPathRoot.getData(CompoundClassPathRoot.java:27)
        at org.pitest.classpath.ClassPath.getClassData(ClassPath.java:97)
        at org.pitest.classpath.ClassPathByteArraySource.getBytes(ClassPathByteArraySource.java:41)
        at org.pitest.classinfo.Repository.querySource(Repository.java:82)
        at org.pitest.classinfo.Repository.nameToClassInfo(Repository.java:68)
        at org.pitest.classinfo.Repository.fetchClass(Repository.java:60)
        at org.pitest.mutationtest.config.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:50)
        at org.pitest.mutationtest.config.LegacyTestFrameworkPlugin.createTestFrameworkConfiguration(LegacyTestFrameworkPlugin.java:36)
        at org.pitest.mutationtest.config.SettingsFactory.getTestFrameworkPlugin(SettingsFactory.java:132)
        at org.pitest.mutationtest.config.SettingsFactory.createCoverageOptions(SettingsFactory.java:140)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:80)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:45)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:118)
        ... 15 more
:pitest FAILED
```

**Comment by szpak** [comment]
@hcoles Is it handled properly in PIT in general?

**Comment by amirfarzad** [comment]
Yes if I exclude the lib files.
Here (https://groups.google.com/forum/#!topic/pitusers/wdrBIdevGSU) Henry mentioned it might be an issue in the "pit-gradle-pligin".
I understand it wants to uncompress and open the .jars as well as other lib files in the classpath to potentially mutate test. Though has an issue on .so, .dll, .dylib files in the project.

**Comment by hcoles** [comment]
@szpak I've not had chance to test to confirm, but I don't believe this issue exists with the maven plugin as maven shouldn't be adding these to the classpath.

You'd probably see something like this from Ant if you were to add the libs to the classpath, but that would be user error.

**Comment by amirfarzad** [comment]
I eventually found a way to temporarily solve the issue and run PI-test on my gradle project.
As it is mentioned in the exception message above the dynamoDB lib files `.so, .dll, .dylib` are in gradle cache(`~/.gradle/caches/modules-2/files-2.1`). Actually `com.amazonaws:DynamoDBLocal` downloads them and keeps them in gradle cache.
I wrote a Gradle task that deletes these `.so, .dll, .dylib` lib files from gradle cache and then `finalizedBy` this task by `project.tasks.pitest`. So after Junit and before pitest they are removed. I still have to exclude DB unit tests from PI-test.
If there was a way that PI-test gradle plugin could ignore `.so, .dll, .dylib` that was really great.

**Comment by szpak** [comment]
I will add a filtering mechanism in the Gradle plugin, however, IMHO it would be good to have it in PIT itself to not have to cope with it in sbt and ant separately.

**Comment by szpak** [comment]
@amirfarzad I've made a fix and uploaded a snapshot version to Sonatype repository. Please verify that is solves your problem.

You need to add the snapshot repository, e.g.
```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.1.11-SNAPSHOT'
    }
}
```

Initially I planned to make the exclusions configurable, however there were some implementation issues to handle it in a flexible way to I created a separate issue for that: #53.

**Comment by szpak** [comment]
1.1.11 has just been released.

**Comment by amirfarzad** [comment]
@szpak  Perfect. Yes it solved the problem. Thanks a lot!

**Comment by otsvetkov1** [comment]
I'm still having the problem with version 1.2.2 of the gradle plugin!
