### ISSUE TITLE
Multi-package support for java projects

### ISSUE THREAD

**Issue by jonesg504** [szpak/gradle-pitest-plugin#82]
I have a project that within the src/main/java directory are multiple packages that each contain multiple java classes. Is there a way to tell the PIT tests to test all those java classes without listing them all in the targetClasses array?

**Comment by szpak** [comment]
Have you tried just `['folder.*']`?

The Gradle plugin just pass that value to PIT which - looking at [the documentation](http://pitest.org/quickstart/commandline/) - should handle that.

**Comment by jonesg504** [comment]
Yep I tried that. I tried doing some sourceSet things as well to no avail.

The file structure looks like this
project /
    src /
        main /
            java /
                com /
                    packages /
                        package1 /
                            test.java
                            test2.java
                        package2 /
                            test3.java
                            test4.java
                        package3
                            test5.java
                            test6.java

running with: <targetClasses = ["com.packages.*"]> ends up erroring out when trying to run ./gradlew pitest

**Comment by szpak** [comment]
PIT complains that no classes to mutate were found? Or with any other error?

**Comment by jonesg504** [comment]
It give ```Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.```

**Comment by szpak** [comment]
Could you please run the `pitest` task with `--info` and paste parameters which are passed to PIT? You can remove not related stuff, such as classpath libraries.

**Comment by jonesg504** [comment]
```VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.161-b12
Uptime : 1229
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:103)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:116)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:49)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.161-b12
Uptime : 1228
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:142)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:87)
        ... 6 more

:pitest (Thread[Task worker for ':',5,main]) completed. Took 1.341 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pitest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

Ran with ./gradlew pitest --info

**Comment by jonesg504** [comment]
I have solved the issue, I just created a simple script that parses the src folder and grabs all the packages and pass that as an array to targetClasses

**Comment by jonesg504** [comment]
Its some ugly code, but it works for me
```
ext.getPackages = { ->
    //This is to grab the directory of the source code (grabs /src/main/java)
    def myDir = sourceSets.main.java.getSrcDirs()[0]
    def allPaths = []
    def myPathArrays = []
    def myPaths = []
    //Goes in src/main/java and grabs all subdirectories, then splits the file paths into an array where each index is a folder but excluding src,main and java. (src/main/java/com/project/folder/folder/controller becomes ['com', 'project', 'folder', 'folder', 'controller']) 
    myDir.eachDirRecurse {dir -> allPaths.push(relativePath(dir).split('/')[3..-1])}
    //This line excludes any file path that is not the actual packages (such as com/project/ or just com), in my case the packages are 7 folders deep)
    allPaths.each {array -> (array.size() < 7) ? allPaths.toArray() : myPathArrays.push(array)}
    //Finally I concatenate all the folders putting a "." between each file creating a package name and adding a "*" to the end
    myPathArrays.each {pathArray -> def path = ""; pathArray.each {dir -> path += dir + '.'}; myPaths.push(path + '*')}
    return myPaths
}
```

I put this snippet in a file called common-methods.gradle and in my build.gradle I added the line:
```apply from: "$rootDir/common-methods.gradle"```

**Comment by hcoles** [comment]
@jonesg504 this shouldn't be necessary, pitest has no know issues with multiple packages. In fact this is probably the most common way that it is run (unless I have misunderstood your scenario).

Could you post the process parameters produced by the info command?
